
@Test([], "success(23)")
function myCode.listGet1(): Try<Natural2> {
  let emptyList: List<Natural2> = []<Natural2>
  let listOne: List<Natural2> = List.append<Natural2>(emptyList, Natural2."23")
  let listTwo: List<Natural2> = List.append<Natural2>(listOne, Natural2."17")
  let listThree: List<Natural2> = List.append<Natural2>(listTwo, Natural2."42")
  List.get<Natural2>(listThree, Natural2."0")
}

@Test([], "success(42)")
function myCode.listGet2(): Try<Natural2> {
  let emptyList: List<Natural2> = []<Natural2>
  let listOne: List<Natural2> = List.append<Natural2>(emptyList, Natural2."23")
  let listTwo: List<Natural2> = List.append<Natural2>(listOne, Natural2."17")
  let listThree: List<Natural2> = List.append<Natural2>(listTwo, Natural2."42")
  List.get<Natural2>(listThree, Natural2."2")
}

@Test([], "42")
function myCode.listGetAssume(): Natural2 {
  let emptyList: List<Natural2> = []<Natural2>
  let listOne: List<Natural2> = List.append<Natural2>(emptyList, Natural2."23")
  let listTwo: List<Natural2> = List.append<Natural2>(listOne, Natural2."17")
  let listThree: List<Natural2> = List.append<Natural2>(listTwo, Natural2."42")
  Try.assume<Natural2>(List.get<Natural2>(listThree, Natural2."2"))
}

@Test([], "failure")
function myCode.listGetOutOfBounds(): Try<Natural2> {
  let emptyList: List<Natural2> = []<Natural2>
  let listOne: List<Natural2> = List.append<Natural2>(emptyList, Natural2."23")
  let listTwo: List<Natural2> = List.append<Natural2>(listOne, Natural2."17")
  let listThree: List<Natural2> = List.append<Natural2>(listTwo, Natural2."42")
  List.get<Natural2>(listThree, Natural2."3")
}
